baseURL = "https://your-site.netlify.app"
title = "Hillary Rogers Travel"
languageCode = "en-us"
theme = "stack"

[params]
  description = "Travel blogger exploring the world and creating Pinterest content"
  defaultTheme = "auto"

[params.sidebar]
  subtitle = "Uganda & Beyond"
  avatar = "/images/avatar.jpg"

[social]
  Pinterest = "https://pinterest.com/yourprofile"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2